apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: backend
  template:
    metadata:
      labels:
        tier: backend
    spec:
      containers:
      - name: k8s-redis
        image: redis

